name: Build and Publish
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v1
      name: Checkout Code
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
     
    - name: Restore NuGet Packages
      run: nuget restore iSuite.sln
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
 
    - name: Build and Publish App
      run: msbuild iSuite.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
 
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      env:
       ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      with:
        name: iSuite_GA
        path: ..\bin\Release\net472\publish\
